version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      ENV_VARIABLE_1: value1
      ENV_VARIABLE_2: value2

  # Add database service (if required)
  # db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: your_mysql_root_password
  #     MYSQL_DATABASE: your_database_name
  #     MYSQL_USER: your_mysql_user
  #     MYSQL_PASSWORD: your_mysql_password
